<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>63a69228-01df-4cec-9fa3-d58e2db2b818</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_docs_intro</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/div[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/docs\/intro']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'navbar__item navbar__link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>navbar__item navbar__link</value>
        <webElementGuid>b9e896d7-61d9-496b-b581-9b77ae85d051</webElementGuid>
    </webElementProperties>
</WebElementEntity>