<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0b47cac7-b8c3-4408-be6f-2b5abe06ddd4</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_app_daily_dev_sources_daily_updates</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/div[1]/div[1]/a[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='https\:\/\/app\.daily\.dev\/sources\/daily_updates']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'navbar__item navbar__link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>navbar__item navbar__link</value>
        <webElementGuid>f79c89db-ba35-4845-badd-ec659dd59c13</webElementGuid>
    </webElementProperties>
</WebElementEntity>